### ISSUE TITLE
Should the readme list >=py38 instead of >=py37 as the autodetected minimum version?

### ISSUE THREAD

**Issue by matrss** [Zac-HD/shed#100]
The latest commit ATM (73ea9159c5cec2c462ce0779457231dc69a79466) drops py37 support. In the features section, the readme lists py37 as the "autodetected minimum version". Should that be py38 now as well, or is this difference intentional?

**Comment by Zac-HD** [comment]
Oops!  The readme needs an update, I'll fix that shortly.  Thanks for the report 😅

**Comment by Zac-HD** [comment]
Fixed in 6bc10985fc2e22f5bd95539e388ca75b3c3da363.
