### ISSUE TITLE
Internal error: with pyupgrade 2.8.0

### ISSUE THREAD

**Issue by lukedyer-peak** [Zac-HD/shed#12]
I've installed `shed` and when trying to run it via command line I get the following error on each of my files:
```
Internal error formatting '<FILE>.py': module 'pyupgrade' has no attribute 'IMPORT_REMOVALS'
```

It looks like the new version of `pyupgrade` 2.8.0 has broken compatibility with `IMPORT_REMOVALS`?  Downgrading to `2.7.4` works as expected.

Here are the relevant package versions: 
```
autoflake-1.4 isort-5.7.0 libcst-0.3.16 pybetter-0.3.6.1 pyemojify-0.2.0 pyupgrade-2.8.0 pyyaml-5.4.1 shed-0.3.1 tokenize-rt-4.1.0 toml-0.10.2 typing-extensions-3.7.4.3 typing-inspect-0.6.0
```

**Comment by lukedyer-peak** [comment]
I forgot to say that this is using python 3.6 but I assume the issue is universal

**Comment by Zac-HD** [comment]
Thanks Luke!  It's a known hazard of `shed`'s design that we're using other people's internals, so things can indeed without much warning.  I'll have a patch out shortly 😄

**Comment by lukedyer-peak** [comment]
Feel free to close #13 as well.  Thought I'd at least give you a temp fix as an easy option

**Comment by Zac-HD** [comment]
Fixed in https://pypi.org/project/shed/0.3.2/

Thanks again for reporting this!
