### ISSUE TITLE
empties my `__init__.py` files

### ISSUE THREAD

**Issue by vdwees** [Zac-HD/shed#16]
By default, autoflake will remove unused imports in `__init__.py` files. However, importing modules into these files and not using them is quite a common pattern, e.g. [isort `__init__.py`](https://github.com/PyCQA/isort/blob/main/isort/__init__.py).

The safest thing would be to disable this behaviour with this autoflake flag: `--ignore-init-module-imports`. Perhaps shed should use this flag?

**Comment by Zac-HD** [comment]
Given the [very strange semantics](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) of star-imports *specifically* from `__init__.py` files *without* `__all__` defined, I consider this additional reason to define `__all__` a non-bug.

Apologies for any inconvenience this may cause; I'll leave the issue open until I add a short explanation to the docs.

**Comment by vdwees** [comment]
I'll preface this comment with this, so you know where I am coming from: I would really like to see a tool like shed succeed, and I am very impressed with the effort you have put so far into it. Being able to tell people at my company to "just use shed" would make me very happy. That's why I'm asking you to give this issue a second thought.

What you propose is an interesting idea for the usage of `__all__` that I am probably unfamiliar with. I am generally of the opinion that star imports are sloppy and reduce the maintainability of code, so I admit I haven't really invested much time with `__all__` either in my code. However, as I understand it, `__all__` allows you to limit star imports to a subset of what has already been imported. This means that in canonical python code, for the case where no such limitation is required, `__all__` is not required either.

The use case have in mind is that many library authors want to define a set of symbols that are available at the top level of their package. A very clean way to do this is to import those symbols from their various submodules into `__init__.py`. In this common case, there is no reason to mess around with `__all__`: only the symbols that you want to export are imported, there is no need to duplicate the symbols as stings into `__all__`.  Of course, you can't always avoid `__all__`, but many maintainers do when possible, for a range of valid reasons: `__all__` is an array of strings instead of symbols, which is error-prone and breaks tab completion on many editors, it is not DRY, etc.

I already linked to the isort `__init__.py` above, but to emphasize my point I will list this pattern being used in a few more highly popular and, in my opinion, well-designed libraries:

https://github.com/tiangolo/fastapi/blob/master/fastapi/__init__.py
https://github.com/MagicStack/asyncpg/blob/master/asyncpg/protocol/__init__.py
https://github.com/PyCQA/isort/blob/main/isort/__init__.py

If you decide that shed should actively oppose this pattern, I look forward to reading about the rationale when you update the docs. That said I would expect that many existing codebases would be forced to pass on shed, certainly I can't tell people at my company anyway to add unneeded `__all__` variables into their codebase, especially when star imports are already discouraged.

**Comment by vdwees** [comment]
In reading more about this topic, I came across this mypy behaviour:
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport
The from-as syntax is preferable to a `__all__` variable, in my opinion.

**Comment by Zac-HD** [comment]
I can see where you're coming from, but I will keep the current behaviour.

- It's the default behaviour in `autoflake` too
- IMO `__all__` is semantically the right way to do this
- I prefer to avoid special cases such as different behaviour per filename

**Comment by vdwees** [comment]
Hmm ok, thanks anyway!

**Comment by vdwees** [comment]
@Zac-HD just want to say you've won me over. thanks for shed :)

**Comment by Zac-HD** [comment]
Aww, thanks! It's always lovely to hear from happy users 🥰
