### ISSUE TITLE
_fix_py36_plus() missing 1 required keyword-only argument: 'min_version'

### ISSUE THREAD

**Issue by luastoned** [Zac-HD/shed#20]
Hello, I just installed shed and received this error:

```
shed src/app.py
Internal error formatting 'src/app.py': _fix_py36_plus() missing 1 required keyword-only argument: 'min_version'
```

I guess `__init__.py#36` should be: `source_code = pyupgrade._main._fix_py36_plus(source_code, min_version=pyupgrade_min)`

**Comment by Zac-HD** [comment]
What versions of shed and pyupgrade are you using?  This is probably an incompatible new version and I'll fix it ASAP 🙂

**Comment by Zac-HD** [comment]
Fixed in https://pypi.org/project/shed/0.3.7/ 😁
