### ISSUE TITLE
flynt for f strings

### ISSUE THREAD

**Issue by mcarans** [Zac-HD/shed#21]
Thanks for a very helpful project!

I have found that pyupgrade does not work as well with converting old strings to f strings as another project called [flynt](https://github.com/ikamensh/flynt) that is dedicated to that task only. 

I'd like to suggest running flynt as part of the process in addition to pyupgrade which does a lot of other stuff as well.

**Comment by Zac-HD** [comment]
Thanks for getting in touch, and for your suggestion!

Having looked into `flynt`, I'm not going to add it - the transformations aren't always safe, and I actually prefer `pyupgrade`'s caution about using complex expressions in f-strings.  I will however list it in the README as a related tool 😁
