### ISSUE TITLE
Emit a warning on invalid syntax in files or in doc code-blocks

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/shed#23]
`echo 1/ > t.py && shed t.py` reports an internal error, because the file contents are not syntactically valid Python.  We should just emit a warning in this case.  CC @rsokl 😉

**Comment by Zac-HD** [comment]
As of `shed == 0.4.1`, this is no longer an error - but we silently skip such broken bits of code, and I'd prefer to emit a warning or print to stderr.  Challenge: thread through a `location` param to use in such a warning, and ideally make it warning when used in code - caught and printed to stderr when in the CLI.

**Comment by rsokl** [comment]
Sorry for not just opening an issue earlier! I can confirm that the internal errors I was getting on `0.3.10`, e.g. 

```
Internal error formatting 'README.md': Cannot parse: 1:0: >>> from hydra_zen import builds
```

were indeed related to me using a `python` code block where I should be using a `pycon` one. I can also confirm that `0.4.1` runs without issue on the same project!

**Comment by Zac-HD** [comment]
Fixed by https://github.com/Zac-HD/shed/commit/c2414fe8dfc8626702978ed7ec2c3951ef1b08a2: from version 0.4.2, `shed` reports

```
$ shed hydra-zen/README.md
Could not parse ```python markdown block in file 'hydra-zen/README.md'
    Perhaps you should use a 'pycon' block instead?
Could not parse ```python markdown block in file 'hydra-zen/README.md'
    Perhaps you should use a 'pycon' block instead?
```

and successfully formats the actually-`python` code blocks in the same pass 🚀
