### ISSUE TITLE
Please clarify the format of the positional file argument?

### ISSUE THREAD

**Issue by salimfadhleyhtp** [Zac-HD/shed#24]
The readme.md / help text only gives the following information about the file argument:
```
positional arguments:
  file         File(s) to format, instead of autodetection
```
It's not clear what this file format is. Are globs allowed, can we do ** subdirectory matching? Could somebody expand the documentation to explain what kinds of values are acceptable?

**Comment by Zac-HD** [comment]
Your shell might handle globbing or ** subdirectory matching for you; but in `shed` I decided to only handle exact (relative or absolute) filenames - I already have one path which uses git to work out which files to format and directories to ignore, and that's both too important to leave out and too painful to build or maintain for a side project.

**Comment by salimfadhleyhtp** [comment]
@Zac-HD when I use black I normally do something like:
```
black ./src
```
Which by default processes every file in the "src" directory. If I try the same in shed I get this:
```
>shed --py39-plus --refactor ./src
skipping './src' due to [Errno 13] Permission denied: './src'
```
Is there a correct way to "process everything in <directory>" with Shed?

**Comment by Zac-HD** [comment]
You can either:

- pass a full list of the files to format
- use pre-commit
- allow shed to find all python in your git repo
