### ISSUE TITLE
Positional file argument does not prevent git repo detection

### ISSUE THREAD

**Issue by lmmx** [Zac-HD/shed#28]
I know this is closed but I don't think it's working as intended:

```sh
$ shed ./box_resize.py 
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

When passed in a positional `file` argument on the command line it is resorting to the git approach. This seems like a bug, as the README says it can be used without a git repo, thought I should let you know

**Comment by Zac-HD** [comment]
Ah, we still try to find a git repo to determine first-party imports - I'd bet `shed` exits cleanly [because the error is handled](https://github.com/Zac-HD/shed/blob/2501f9d0985fa97f233cb2a52d6d0780e089285e/src/shed/_cli.py#L25-L37), we just need to avoid `git` writing to stdout or stderr.

**Comment by lmmx** [comment]
Brill, cheers that fixes it! :rocket::rocket::rocket:
