### ISSUE TITLE
Bump black version in setup.py please

### ISSUE THREAD

**Issue by asvetlov** [Zac-HD/shed#29]
The problem is:
- pre-commit caches installed hook, the cache key is repo tag
- black published 22.1.0 release 3 days ago
- https://pre-commit.ci uses cached shed==0.8.0 which has black>=21.12b0, (black==21.12b0 was cached by pre-commit.ci internally)
- when I run pre-commit hooks locally it uses black==22.1.0 if installed from fresh (or after `pre-commit clean` command)

As the result, https://pre-commit.ci and my local pre-commit install have different `black` versions and reformat files differently.
The black version bump in `setup.py` solves the problem.
To prevent it in future I can suggest pinning all requirements to strict versions in `pre-commit-hooks.yaml`. `additional_dependencies: [".[pre-commit]"]` record can enforce `pre-commit` extra dependency that pins all requirements from open-ranged deps to strict ones, e.g. `autoflake >= 1.4` from `install_requires` should be converted into `autoflake == 1.4` in `extra_requires` section.
Keeping `extra` deps versions can be tedious a little, I believe Dependabot can automate everything except publishing a new tag maybe (it is up to you, I personally prefer to forbid bots initiating a new release process).

If you agree with the proposed strategy and have no time for implementing it yourself, I'm happy to master a PR. Should be an easy task, sure.

**Comment by Zac-HD** [comment]
I'm planning to release a new version which requires `black >= 22.1.0` this evening - this got us at work too :sweat_smile: 

I'm unwilling to require exact versions though, even as an extra - that always goes wrong eventually.  In any case this is a generic problem which applies to *any* tool used through `pre-commit`: they don't pin transitive dependencies at all!  I'm therefore *also* unwilling to take on an extra maintainence task here which could be solved once and for all upstream, e.g. by using the latest dependencies *published before* the top-level pinned version.

**Comment by asvetlov** [comment]
Thanks for your quick response!
Sure, the mentioned `pip` mode can solve the problem for all hooks.
