### ISSUE TITLE
VSCode auto-format using shed

### ISSUE THREAD

**Issue by tclasen** [Zac-HD/shed#30]
Current I'm using black to auto-format my code on save when using VSCode, there is a setting in .vscode/settings.json here you specify the path to the black binary if it isn't in your path. I tried the following, but it doesn't work as I had hoped it to:

    "python.formatting.blackPath": "./.venv/bin/shed",
    "python.formatting.provider": "black",

Is there another way to hook up shed to VSCode or is there possibly a way for my above example to work?

**Comment by Zac-HD** [comment]
I'd recommend using `black` to format on save, and setting up `shed` to run when you commit or push - removing "unused" imports when you save - just before using them - isn't really that helpful!

**Comment by Zac-HD** [comment]
If you want to `shed`-on-save anyway go ahead, but I don't know how to set that up sorry.
