### ISSUE TITLE
--refactor runs into an error with some f-string syntax like f"{var=}"

### ISSUE THREAD

**Issue by TheSkeward** [Zac-HD/shed#31]
I have a line of code in my project that looks like:
```
logging.info(f"{OMEGA.message_cache=}, {len(OMEGA.user_cache)=}, "
                 f"{OMEGA.message_cache / max(len(OMEGA.user_cache), 1)=}")
```
`shed` works fine but when using `shed --refactor` it stalls here:
```
Internal error formatting 'main.py': ParserSyntaxError: Syntax Error @ 794:31.
Incomplete input. Encountered '=', but expected '!', ':', or '}'.

        f"{OMEGA.message_cache=}, {len(OMEGA.user_cache)=}, "
                              ^
    Please report this to https://github.com/Zac-HD/shed/issues
```

**Comment by Zac-HD** [comment]
Hmm, looks like failed version detection. Does passing --py38-plus fix it, as a quick workaround?

**Comment by TheSkeward** [comment]
yep, works fine with `shed --refactor --py38-plus`

**Comment by Zac-HD** [comment]
Yep, the underlying problem is that Black doesn't detect f-strings with `=` as requiring Python 3.8.

I've just release `shed 0.9.2` with a workaround, https://github.com/Zac-HD/shed/commit/5724e7f5da6c9eefc0f65dc7f9aeb083a3a04a46.  Thanks for reporting!
