### ISSUE TITLE
pyupgrade._main has no attribute _fix_py36_plus

### ISSUE THREAD

**Issue by Charlie-Root** [Zac-HD/shed#41]
When running shed i receive the following error:
`Internal error formatting 'vworker/helpers/amp.py': AttributeError: module 'pyupgrade._main' has no attribute '_fix_py36_plus'
    Please report this to https://github.com/Zac-HD/shed/issues`

Tested this on multiple files and using all possible flags to run shed.

**Comment by Zac-HD** [comment]
Already fixed in the latest version of `shed`.
