### ISSUE TITLE
Issues loading files containing unicode on windows

### ISSUE THREAD

**Issue by phillco** [Zac-HD/shed#42]
We recently added Shed to our [project](https://github.com/knausj85/knausj_talon) via pre-commit and are pretty happy with it.

However, our Windows users discovered that `shed` won't run on any Python file that contain Unicode:

```
skipping 'code/dictation.py' due to 'charmap' codec can't decode byte 0x9d in position 3481: character maps to <undefined>"
```

The [root issue](https://github.com/knausj85/knausj_talon/issues/875) has more detail, but basically it seems like Windows' default behavior for `open()` is to use the platform-default encoding (cp1252) instead of UTF-8, so it fails at [this `open()` call](https://github.com/Zac-HD/shed/blob/master/src/shed/_cli.py#L60).

It looks like Black uses the [tokenize](https://docs.python.org/3/library/tokenize.html) library to open Python files, which automatically [detects encoding](https://docs.python.org/3/library/tokenize.html#tokenize.detect_encoding), so perhaps all we need to do is replace it with [`tokenize.open`](https://docs.python.org/3/library/tokenize.html#tokenize.open) if the file is Python?

Alternatively, if the goal is for Shed to be "maximally opinionated" then maybe we should just add `encoding="utf8"` to that open call? :)

## Reproduction steps:

1. Clone https://github.com/knausj85/knausj_talon on Windows
2. Run `shed`, it should fail with the above error because of the unicode characters in https://github.com/knausj85/knausj_talon/blob/master/code/dictation.py

**Comment by Zac-HD** [comment]
Thanks for the report!  This should be fixed in https://github.com/Zac-HD/shed/commit/a757277a3ca282769fd7a60a8a844c4a87f68d00, the new version 0.10.1 😁

**Comment by phillco** [comment]
Excellent, thanks!

**Comment by phillco** [comment]
Confirmed that `0.10.1` fixes it on Windows :)

<img width="771" alt="Screen Shot 2022-06-07 at 10 03 35 AM" src="https://user-images.githubusercontent.com/536668/172441141-02d2fcfc-e391-4da5-aba4-fbe6d6aaf4be.png">
