### ISSUE TITLE
Option to list files that were reformatted

### ISSUE THREAD

**Issue by phillco** [Zac-HD/shed#43]
One thing I've noticed about using `shed` inside of pre-commit is that it doesn't list the files that it reformatted/fixed the way that Black (or https://github.com/pre-commit/pre-commit-hooks) do.

This can make it a little bit hard to observe what needed to be reformatted or what the formatter did.

Black:

```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted cherry_picker.py
```

Shed:

```
shed.....................................................................Failed
- hook id: shed
- files were modified by this hook
```

I realized this is probably more difficult because it involves combining the actions of different formatters, but think it would be nice to have a flag for this. (Or, imo, just make it the default behavior -- I think this would be a further advantage of `shed` over a variety of separate formatters, because you would get one complete list of Python files changed).

**Comment by Zac-HD** [comment]
I can see the argument in favor, but I really really really value not having configuration options, and prefer the unix "silence is golden" tradition as a default.  Sorry!
