### ISSUE TITLE
chokes on ipython magics in Jupyter notebooks

### ISSUE THREAD

**Issue by ltalirz** [Zac-HD/shed#44]
Python code cells in Jupyter notebooks can contain code that is not valid Python, like

```
%load_ext my extension
```
or 
```
!command
```

`shed` currently fails on Jupyter notebooks in Jupytext that contain such blocks with an error like
```
Could not parse ```python markdown block in file 'myfile.md'
```

Example notebook
~~~markdown
---
jupyter:
  jupytext:
    text_representation:
      extension: .md
      format_name: markdown
      format_version: '1.3'
      jupytext_version: 1.13.4
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```python
%load_ext autoreload
```

```python
!ls /dev
```

```python
valid = 'python'
```
~~~

It's not entirely clear to me who's at fault here - jupytext or shed.
The code blocks declare themselves as `python` (which they are not). I guess in the medium term one might also consider adding a new, more specific MarkDown code-block identifier for Jupyter notebook cells.

**Comment by Zac-HD** [comment]
I wouldn't describe Jupytext as being *at fault* here, but this is definitely put of scope for shed. Sorry for the inconvenience!
