### ISSUE TITLE
pyupgrade v3: Internal error formatting '...': AttributeError: module 'pyupgrade._main' has no attribute 'IMPORT_REMOVALS'

### ISSUE THREAD

**Issue by The-Compiler** [Zac-HD/shed#48]
https://github.com/Zac-HD/shed/blob/6abc9b62de9e788d54cfaf25228e3310c18353be/src/shed/__init__.py#L160

seems to have been removed in the recent pyupgrade v3 [release](https://pypi.org/project/pyupgrade/#history): https://github.com/asottile/pyupgrade/commit/57eb8ab065eac794deebfb91f20768b3b8455eef

which leads to:

```
Internal error formatting '...': AttributeError: module 'pyupgrade._main' has no attribute 'IMPORT_REMOVALS'
    Please report this to https://github.com/Zac-HD/shed/issues
```

**Comment by Zac-HD** [comment]
Thanks for the quick report!  Fixed and shipped 🚀

**Comment by The-Compiler** [comment]
That sure was a quick fix - thank *you*!
