### ISSUE TITLE
Support Jupyter notebooks

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/shed#5]
If passed an `.ipynb` file, or a repo containing them, apply `shed` to each code cell using https://github.com/jupyter/nbformat  This should be an optional extra, with the caveat that `shed` will raise an error telling you to install `shed[notebook]` if run on a `.ipynb` file otherwise (or print a warning if they're just in a repo).

Shipping a Jupyter plugin to automatically format code cells immediately before execution would be very cool, but perhaps out of scope for now.

**Comment by Zac-HD** [comment]
On further thought, deleting unused imports and variables doesn't mix will with cell-structured code :sweat_smile:

**Comment by MarcoGorelli** [comment]
Hi @Zac-HD 

Just FYI, [nbQA](https://github.com/nbQA-dev/nbQA) will do this

**Comment by Zac-HD** [comment]
Sweet!  I might try integrating this so it's totally automatic for the user; if not it will at least have a place in the README 😁
