### ISSUE TITLE
Add option to recursively format all files in a specific folder

### ISSUE THREAD

**Issue by 34j** [Zac-HD/shed#50]
Since shed has the ability to specify which files to format, I would like to request this feature. `autoflake`, `isort`, and `black` all have this feature, so it would not be a bad idea for shed to have this feature.

If implemented like `autoflake`, it would be like:

```
shed -r /path/to/folder
```

If implemented like `isort` or `black`:

```
shed /path/to/folder
```

I am sorry in advance, but I will not have time to implement this feature.  If you don't like it, please close it.

**Comment by Zac-HD** [comment]
It might be convenient, but it's also a surprisingly difficult thing to get right with good performance!  I'd rather encourage users to use git, pre-commit, or other tools to solve this (rare) problem and spend my time improving the refactoring logic.
