### ISSUE TITLE
Missing pre-commit-config.yaml ?

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/shed#54]
I'm failing to run pre-commit on this repo, it saying `.pre-commit-config.yaml is not a file` (also failing to run it by installing and such). Is it supposed to work with just a hooks file?

**Comment by Zac-HD** [comment]
We don't actually have pre-commit configured to use *in* this repo; just to treat it as a hook!  It's small enough that bare `shed` is super fast anyway 🤷‍♂️

**Comment by jakkdl** [comment]
Oh derp, the hook file is so you can hook the repo. Everything makes sense now! :sweat_smile:
