### ISSUE TITLE
Refactor visitor silently not run if there's syntax error in files

### ISSUE THREAD

**Issue by jakkdl** [Zac-HD/shed#55]
It's bitten me several times, so I'd like to fix this before the next time I work on this.

Example:
tests/recorded/foo.txt
```
bool(len([1, 2]))
foo((5))

================================================================================

bool([1, 2])
foo(5)
```

but if we introduce a syntax error, the reformatter isn't run and all tests would pass with a file like this:
```
bool(len([1, 2]))
foo((5)

================================================================================

bool(len([1, 2]))
foo((5)
```

**Comment by jakkdl** [comment]
(bit me again, grrr)

temp workaround for me is to remove
```python
        warnings.simplefilter("ignore", shed.ShedSyntaxWarning)
```
from `tests/test_expected_output.py`, it breaks a bunch of other tests but mine aren't affected at least.

**Comment by Zac-HD** [comment]
I think for this we can update the *test* instead, to fail if the input portion has invalid syntax (checking with `compile()`), which should be a tiny diff.
