### ISSUE TITLE
Support for check

### ISSUE THREAD

**Issue by pamelafox** [Zac-HD/shed#58]
We're interested in running shed as a Github action to check if contributors ran shed, but we are hoping to have check support (running each of the linters in --check mode). Have you considered support for check? I think it would mean passing through the flag to each of the underlying tools, but I'm not certain that all of them support check (I know isort/black do).

Thanks!

**Comment by Zac-HD** [comment]
Hi Pamela - glad you're finding `shed` useful!

To keep maintenance manageable I want to avoid adding configuration options; even `--refactor` was a bit painful tbh.  However I've found `shed && git diff --exit-code` to be a good way of checking this in CI, [including for this very repo](https://github.com/Zac-HD/shed/blob/c111369e16f10b5a30d0d2c46d2ecf31e2f0ee45/.github/workflows/ci.yml#L22-L23).
