### ISSUE TITLE
Ruff auto-fixes

### ISSUE THREAD

**Issue by TomFryers** [Zac-HD/shed#64]
[Ruff](https://github.com/charliermarsh/ruff) supports a considerable number of auto-fixes. It might be worth using for Shed. It's ‘extremely fast’, and may be able to replace some of the other things Shed runs, as well as adding extra rewrites.

**Comment by Zac-HD** [comment]
Unfortunately Ruff doesn't yet support all python 3.9 syntax, let alone 3.10 or 3.11, so it's generally not a viable replacement (yet). On the other hand, it does keep improving and I'd be pretty happy if it obsoleted shed someday 😁

**Comment by ThatXliner** [comment]
It's compatible with Python 3.11 now

**Comment by auscompgeek** [comment]
Ruff still doesn't support all Python 3.10 syntax. From its readme:

> Ruff does not yet support structural pattern matching.

**Comment by henryiii** [comment]
Ruff fully supports all Python syntax now up to 3.11 (as of 0.0.250), including pattern matching.

I've converted cibuildwheel, pybind11 (python & cmake examples too), scikit-build,
scikit-build-core, awkward, boost-histogram, hist, uhi, vector, GooFit, the
Scikit-HEP Developer pages and scikit-hep/cookie, scikit-hep-repo-review, nox,
plumbum, particle, decaylanguage, uproot, and uproot-browser, and maybe others.
Other packages have moved over too, like Pandas, build, FastAPI, Apache
Airflow, and SciPy.

The scikit-build example of pybind11 uses `shed`, though, so it's one remaining place I don't have Ruff.
