### ISSUE TITLE
add upper bound for black and isort versions

### ISSUE THREAD

**Issue by ghazi-git** [Zac-HD/shed#70]
Yesterday, black released v23.1 which has breaking changes in formatting. So, github checks for my PRs started failing due to that and I had to first apply the formatting changes before being able to merge the PR.

To me, it didn't feel right that without any change in the version of shed I'm using, there still were changes in how code is formatted. So, I thought maybe this is a valid case for adding an upper bound to black version. I understand it's usually a bad idea to add an upper version bound but I thought this might be a valid exception given [black commitment to no formatting changes in a single calendar year](https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy).

I did a quick check to see if sth similar can be done for the rest of the tools. It looks like [isort has a similar commitment](https://pycqa.github.io/isort/docs/major_releases/release_policy.html#formatting-guarantees), but didn't see sth like it for autoflake, pyupgrade and blacken-docs. I thought maybe the solution is to pin the rest of the tools but that also has its downsides and especially the maintenance burden of having to create a new shed release for each dependency release.

So, as a middle ground, what do you think about adding upper bounds for black and isort given their commitment to, at least, minimize formatting changes despite no shed version change?

**Comment by Zac-HD** [comment]
Fair question - in fact I just released `shed == 0.10.9` which updates the *lower* bound of Black!

 See https://iscinumpy.dev/post/bound-version-constraints/ for the detailed arguments against upper-bound versions (even just the introduction!), and for an example of pinning transitive deps see https://github.com/Zac-HD/shed/blob/edaddee197883fc6c31e818acc62f267609fa489/tox.ini#L27-L33

**Comment by ghazi-git** [comment]
I think I should have added more context to the initial question.

I actually read the [TLDR](https://iscinumpy.dev/post/bound-version-constraints/#tldr) of that very article before posting and that's why I wrote 
> I understand it's usually a bad idea to add an upper version bound

My basis for the suggestion is this
> Only add a cap if a dependency is known to be incompatible or there is a high (>75%) chance of it being incompatible in its next release.

and with black and isort, there is a high probability for formatting changes release in v24 and v6 respectively. Also, when I read
> A library is not installed in isolation;

I thought: since shed is usually used as a pre-commit hook (which installs everything in isolation), maybe that's why we can break the rule.

Also, I was very hopeful since you did release a new version right after black released
> If you absolutely must set upper limits, you should release a new version as soon as possible with a higher cap when a dependency updates (ideally before the dependency releases the update).

**Comment by Zac-HD** [comment]
Basically I think that everyone should pin their transitive dependencies; helping to avoid that isn't really helping in the long run!  That `pre-commit` lacks a good mechanism for this is an ongoing frustration to me 😅 

And while I updated quickly this time, I don't promise fast updates in general ('[provide the program "as is"](https://github.com/Zac-HD/shed/blob/edaddee197883fc6c31e818acc62f267609fa489/LICENSE#L589-L596)', as the saying goes)

**Comment by Zac-HD** [comment]
Yeah, that's *a mechanism* for pinning dependencies, but it doesn't handle transitive deps or have any upgrade mechanism 🤷‍♂️
