### ISSUE TITLE
After next `autoflake` release, grab the perf improvement

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/shed#88]
https://github.com/PyCQA/autoflake/pull/232 is now merged - so the temporary fix of running isort twice can be removed as soon as a new version is released and we update the minimum required version.

(via https://github.com/Zac-HD/shed/issues/78#issuecomment-1464797492)

**Comment by Cheukting** [comment]
I think the fix is incorporated in v2.0.2, shall the min version be 2.0.2 or 2.1.0 (next minor release)

**Comment by Zac-HD** [comment]
Might as well be 2.1.0, `shed` doesn't aim for long compatibility windows (unlike Hypothesis)

**Comment by Zac-HD** [comment]
Handled in https://github.com/Zac-HD/shed/pull/105 🙂
